apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-consensus-client
data:
  start.sh: |-
    #!/bin/sh
    exec lighthouse beacon_node \
              --log-format=JSON \
              --datadir=/data \
              --enr-tcp-port=9000 \
              --enr-udp-port=9000 \
              --listen-address=0.0.0.0 \
              --port=9000 \
              --discovery-port=9000 \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5052 \
              --metrics \
              --metrics-address=0.0.0.0 \
              --metrics-port=5054 \
              --execution-jwt=/data/jwt.hex \
              --execution-endpoint="http://zeus-exec-client:8551"
  download.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --clientName="lighthouse" --protocol="eth" --network="mainnet" --workload-type="beacon" --bearer="${BEARER}"
  pause.sh: |-
    #!/bin/sh
    exec sleep 100000000000000000
  lodestarGoerli.sh: |-
    #!/bin/sh
    exec node /usr/app/node_modules/.bin/lodestar beacon \
              --dataDir /data \
              --network goerli \
              --rest \
              --execution.urls http://zeus-exec-client:8551 \
              --rest.address 0.0.0.0 \
              --rest.namespace '*' \
              --rest.port 9596 \
              --metrics --logFile /logs/beacon.log \
              --logFileLevel debug \
              --logFileDailyRotate 5 \
              --jwt-secret /data/jwt.hex
  lodestarEphemeral.sh: |-
    #!/bin/sh
    exec node /usr/app/node_modules/.bin/lodestar beacon \
              --dataDir /data \
              --paramsFile=/data/testnet/chainspec.json \
              --rest \
              --execution.urls http://zeus-exec-client:8551 \
              --rest.address 0.0.0.0 \
              --rest.namespace '*' \
              --rest.port 9596 \
              --metrics --logFile /logs/beacon.log \
              --logFileLevel debug \
              --logFileDailyRotate 5 \
              --jwt-secret /data/jwt.hex
  lighthouse.sh: |-
    #!/bin/sh
    exec lighthouse beacon_node \
              --log-format=JSON \
              --datadir=/data \
              --enr-tcp-port=9000 \
              --enr-udp-port=9000 \
              --listen-address=0.0.0.0 \
              --port=9000 \
              --discovery-port=9000 \
              --metrics \
              --metrics-address=0.0.0.0 \
              --metrics-port=5054 \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5052 \
              --execution-jwt=/data/jwt.hex \
              --execution-endpoint="http://zeus-exec-client:8551"
  hercules.sh: |-
    #!/bin/sh 
    hercules
  herculesEphemeral.sh: |-
    #!/bin/sh 
    hercules --network="ephemery" --clientName="lighthouse"
  herculesLighthouseEphemeral.sh: |-
    #!/bin/sh 
    hercules --network="ephemery" --clientName="lighthouse"
  herculesLodestarEphemeral.sh: |-
    #!/bin/sh 
    hercules --network="ephemery" --clientName="lodestar"
  downloadLighthouseEphemeral.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --clientName="lighthouseEphemeral" --network="ephemery" --protocol="eth"
  downloadLodestarEphemeral.sh: |-
    #!/bin/sh
    exec snapshots --downloadURL="" --clientName="lodestarEphemeral" --network="ephemery" --protocol="eth"
  lighthouseEphemeral.sh: |-
    #!/bin/sh
    exec lighthouse beacon_node \
              --log-format=JSON \
              --execution-jwt=/data/jwt.hex \
              --execution-endpoint="http://zeus-exec-client:8551" \
              --testnet-dir=/data/testnet \
              --datadir=/data \
              --enr-tcp-port=9000 \
              --enr-udp-port=9000 \
              --metrics \
              --metrics-address=0.0.0.0 \
              --metrics-port=5054 \
              --listen-address=0.0.0.0 \
              --port=9000 \
              --discovery-port=9000 \
              --http \
              --http-address=0.0.0.0 \
              --http-port=5052 \
              --boot-nodes="enr:-Iq4QGdecZrX_n9aWd0T0r3w9aVTnjbrO9nyDSMunKwxh6M3fkTuDamFtcu4Ulgq82WA7V10XJJJgDFUqrYEGAonNGiGAYSHF-YRgmlkgnY0gmlwhIjzHgyJc2VjcDI1NmsxoQJDyix-IHa_mVwLBEN9NeG8I-RUjNQK_MGxk9OqRQUAtIN1ZHCCIyg,enr:-Ly4QCLjeoItd4CpnAm524ZO4NWZipkQxnal6fm3QU9LvRbiSImfn4hvDGxe9wtAZRVk5WudniqRtnYo-fmsmBo9Fi0Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDGUVuCMAAQGP__________gmlkgnY0gmlwhIe1jKiJc2VjcDI1NmsxoQJN-fBhwvE0x2osJPG3V9UtqACpngpJAG1KFOaRz9voT4hzeW5jbmV0cwCDdGNwgiNQg3VkcIIjUA,enr:-Jq4QLz5xnHfiSTMnzgp20cY6uWI-jiIcFAOVw55cYuUdcFhDR1AB3jb_O-5k97k8X78zkg8zeroLZQD4iJ5Qa5xUyQBhGV0aDKQxlFbgjAAEBj__________4JpZIJ2NIJpcISI8x4MiXNlY3AyNTZrMaECz28TxI2TLY8Z_u_u-Q7rDtBw4KFe9Hta5tAP1WCjOYGDdWRwgiMp"
    
