package web3signer_cmds_ai_generated

var Web3SignerAPICmd = Web3SignerCmdArgs{
	Config: Config{
		ConfigFile:     "",
		DataPath:       "",
		KeyStorePath:   "",
		LoggingLevel:   "",
		HTTPCors:       "",
		HTTPListen:     "0.0.0.0",
		HTTPListenPort: 0,
		HTTPAllowlist:  "*",
		MetricsEnabled: false,
		MetricsPort:    0,
		MetricsPrefix:  "",
	},
	TLSOpts: TLSOpts{
		TLSKeyStoreFile:     "",
		TLSPasswordFile:     "",
		TLSAllowCAClients:   false,
		TLSAllowAnyClient:   true,
		TLSKnownClientsFile: "",
	},
	AWSCfg:      AWSCfg{},
	AzureConfig: AzureConfig{},
	SlashingConfig: SlashingConfig{
		ProtectionDbPassword:           "",
		ProtectionDbUrl:                "",
		ProtectionDbUsername:           "",
		ProtectionEnabled:              false,
		ProtectionDisabled:             true,
		ProtectionPruningEnabled:       false,
		ProtectionPruningEpochsToKeep:  0,
		ProtectionPruningInterval:      0,
		ProtectionPruningSlotsPerEpoch: 0,
	},
	KeyManagerConfig: KeyManagerConfig{
		KeyManagerAPIEenabled:  true,
		KeystoresPasswordFile:  "",
		KeystoresPasswordsPath: "",
		KeystoresPath:          "",
		Network:                "minimal",
	},
}

var Web3SignerStd = Web3SignerCmdArgs{
	Config: Config{
		ConfigFile:     "",
		DataPath:       "",
		KeyStorePath:   "",
		LoggingLevel:   "",
		HTTPCors:       "",
		HTTPListen:     "0.0.0.0",
		HTTPListenPort: 0,
		HTTPAllowlist:  "*",
		MetricsEnabled: false,
		MetricsPort:    0,
		MetricsPrefix:  "",
	},
	TLSOpts: TLSOpts{
		TLSKeyStoreFile:     "",
		TLSPasswordFile:     "",
		TLSAllowCAClients:   false,
		TLSAllowAnyClient:   true,
		TLSKnownClientsFile: "",
	},
	AWSCfg:      AWSCfg{},
	AzureConfig: AzureConfig{},
	SlashingConfig: SlashingConfig{
		ProtectionDbPassword:           "${WEB3SIGNER_SLASHING_PROTECTION_DB_PASSWORD}",
		ProtectionDbUrl:                "${WEB3SIGNER_SLASHING_PROTECTION_DB_URL}",
		ProtectionDbUsername:           "${WEB3SIGNER_SLASHING_PROTECTION_DB_USERNAME}",
		ProtectionEnabled:              true,
		ProtectionPruningEnabled:       false,
		ProtectionPruningEpochsToKeep:  0,
		ProtectionPruningInterval:      0,
		ProtectionPruningSlotsPerEpoch: 0,
	},
	KeyManagerConfig: KeyManagerConfig{
		KeyManagerAPIEenabled:  true,
		KeystoresPasswordFile:  "",
		KeystoresPasswordsPath: "",
		KeystoresPath:          "",
		Network:                "${WEB3SIGNER_NETWORK}",
	},
}
