# This is a sample config file for the serverless build.

########################################
# AWS settings (internal access)
########################################
# if using aws automation, don't share these values with anyone including us these are your private credentials
AWS_ACCOUNT_NUMBER: "" # required for aws automation
# your aws account number should not have dashes here, even thought it is displayed with dashes in the UI
AWS_ACCESS_KEY: "" # required for aws automation
AWS_SECRET_KEY: "" # required for aws automation

# ACTIONS
AWS_AUTOMATION: "true" # required to be true for aws automation, AUTOMATION_STEPS="all" will set this to true

########################################
# AWS Lambda Values (external access)
########################################
# (if you have a lambda function, otherwise you can let the app install and generate these values for you)
# You share these values with us, so we can send message to your lambda function for your validators
AWS_LAMBDA_FUNC_URL: ""
AWS_AGE_DECRYPTION_SECRET_NAME: ""
# This tells the lambda function what secret to use to decrypt your validator keys to sign messages
AWS_EXTERNAL_ACCESS_KEY: ""
AWS_EXTERNAL_SECRET_KEY: ""
# Age encryption private, public key values used to encrypt all your validator keys in a single file.
# If you don't have one, you can let the app generate one for you. If using the aws automation, it will also save
# it in secret manager for you as well
AGE_PRIVKEY: ""
AGE_PUBKEY: ""

# ACTIONS
KEYGEN_SECRETS: "true"

#############################
# Validator network settings
#############################

NODE_URL: "https://eth.ephemeral.zeus.fyi"
NETWORK: "ephemery"

## Validator deposit & keystore generation settings ##
ETH1_PRIVATE_KEY: ""
# This eth1 key (ecdsa) is used to send the validator deposit txs, it should have 32 ETH + gas to send the txs per validator
MNEMONIC_24_WORDS: ""
HD_WALLET_PASSWORD: ""
# If you don't have one, you can let the app generate them for you.
# If using the aws automation, it will also save it in secret manager for you as well
VALIDATORS_COUNT: "3"
# If generating new keystores, e.g. you have generated 10 from your master hd seed,
# but now want to add 10 more, add the offset here to start from the Nth offset validator onwards
HD_OFFSET_VALIDATORS: "0"
KEYSTORE_DIR_IN: "./serverless/keystores"
KEYSTORE_DIR_OUT: "./serverless/keystores"
# These are relative to the ./builds/serverless/ directory
# If you have existing deposit data & validator keystores, you can copy them to the ./builds/serverless/keystores/ directory

# ACTIONS
KEYGEN_VALIDATORS: "true" # if you have existing keystores, set this to false
SUBMIT_DEPOSITS: "true" # if you have existing validators already deposited, set this to false

######################################
## Validator service values for Zeus ##
######################################
BEARER: ""
# You need a bearer token to request validator service from us
# If you don't have one, you can request one from us
# Set a key group name to group your validators together
KEY_GROUP_NAME: ""
# By default, it uses this fee recipient address, for all your validators in your key group,
# but you can override it per validator if you want here:
# builds/serverless/aws_automation/validators_service_requests.go
FEE_RECIPIENT_ADDR: ""

# ACTIONS
SUBMIT_SERVICE_REQUEST: "false"


######################################
##    Automation Step Selection     ##
######################################

# you can replace all with a comma separated list of steps to run
# e.g. only run step 7 to verify the lambda function
# or only step 9 to send the validator deposits

# STEP "1", "createSecretsAndStoreInAWS"
# STEP "2", "createInternalLambdaUser":
# STEP "3", "generateValidatorDeposits":
# STEP "4", "createLambdaFunctionKeystoresLayer":
# STEP "5", "createLambdaFunction":
# STEP "6", "createExternalLambdaUser":
# STEP "7", "verifyLambdaFunction":
# STEP "8", "createValidatorServiceRequestOnZeus":
# STEP "9", "sendValidatorDeposits":

# ACTIONS keywords
# all        - will run steps 1-9
# serverless - will run steps 1-7

# HELPERS: keywords
# use these keywords to fetch the secrets from aws secret manager and print them to the console

# getAgeEncryptionKeySecret
# getMnemonicHDWalletPasswordSecret
# getExternalLambdaAccessKeys

AUTOMATION_STEPS: "all"
