apiVersion: v1
kind: Service
metadata:
  name: zeus-exec-client
  labels:
    app.kubernetes.io/name: zeus-exec-client
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/managed-by: zeus
spec:
  type: ClusterIP
  ports:
    - port: 9003
      targetPort: hercules
      protocol: TCP
      name: hercules
    - port: 30303
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: 30303
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: 8545
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: 8546
      targetPort: ws-rpc
      protocol: TCP
      name: ws-rpc
    - port: 8551
      targetPort: auth-rpc
      protocol: TCP
      name: auth-rpc
    - port: 6060
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 80
      targetPort: http-rpc
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: zeus-exec-client
    app.kubernetes.io/instance: zeus-exec-client

