apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeus-exec-client
  labels:
    app.kubernetes.io/name: zeus-exec-client
    app.kubernetes.io/instance: zeus-exec-client
    app.kubernetes.io/managed-by: zeus
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeus-exec-client
      app.kubernetes.io/instance: zeus-exec-client
  serviceName: zeus-exec-client
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeus-exec-client
        app.kubernetes.io/instance: zeus-exec-client
      annotations:
        {}
    spec:
      initContainers:
        - name: init-chown-data
          image: "busybox:1.34.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "10001:10001", "/data"]
          resources:
            {}
          volumeMounts:
            - name: exec-client-storage
              mountPath: "/data"
        - name: init-snapshots
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/download.sh" ]
          resources:
            {}
          volumeMounts:
            - name: cm-exec-client
              mountPath: "/scripts"
            - name: exec-client-storage
              mountPath: "/data"
      containers:
        - name: hercules
          image: "zeusfyi/hercules:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/hercules.sh" ]
          volumeMounts:
            - name: exec-client-storage
              mountPath: "/data"
            - name: cm-exec-client
              mountPath: "/scripts"
          ports:
            - name: hercules
              containerPort: 9003
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: hercules
        - name: zeus-exec-client
          image: "ethereum/client-go:v1.10.23"
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh" ]
          args: [ "-c","/scripts/start.sh" ]
          volumeMounts:
            - name: exec-client-storage
              mountPath: "/data"
            - name: cm-exec-client
              mountPath: "/scripts"
          ports:
            - name: p2p-tcp
              containerPort: 30303
              protocol: TCP
            - name: p2p-udp
              containerPort: 30303
              protocol: UDP
            - name: http-rpc
              containerPort: 8545
              protocol: TCP
            - name: ws-rpc
              containerPort: 8546
              protocol: TCP
            - name: auth-rpc
              containerPort: 8551
              protocol: TCP
            - name: metrics
              containerPort: 6060
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            tcpSocket:
              port: http-rpc
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: http-rpc
          resources:
            {}
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      terminationGracePeriodSeconds: 300
      volumes:
        - name: cm-exec-client
          configMap:
            name: cm-exec-client
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: exec-client-storage
        annotations:
          {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "2Ti"
