/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    mockingbird: [{type: 'autogenerated', dirName: 'mockingbird'}],
    lb: [{type: 'autogenerated', dirName: 'lb'}],
    zK8s: [{type: 'autogenerated', dirName: 'zK8s'}],
};

module.exports = sidebars;
